name: inspired
favicon: null
layout_spectrum: 0.94745
typography_spectrum: 0.20751
title: Inspired
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#676668'
    - '#19191a'
    - '#41424b'
    - '#99d1ff'
    - '#ddddde'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
