name: inspired
favicon: null
layout_spectrum: 0.8905
typography_spectrum: 0.46996
title: Inspired
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdea35'
    - '#f6f5f1'
    - '#070b0e'
    - '#3e403f'
    - '#858583'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
