name: inspired
favicon: null
layout_spectrum: 0.14813
typography_spectrum: 0.20751
title: Inspired
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edae00'
    - '#e9e7ea'
    - '#000000'
    - '#4f4f4f'
    - '#d7030a'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
