name: inspired
favicon: null
layout_spectrum: 0.8312
typography_spectrum: 0.01497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.4594484071712941
  saturation: 0.18235297757200897
  rhythmicContrast: 0.23666865145787597
purpose: []
