layout_spectrum: 0.7175122785847634
typography_spectrum: 0.691715775988996
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7543973396532238
  lightness: 0.9236963079310954
  saturation: 0.35259488923475146
  rhythmicContrast: 0.35876828245818615
name: inspired
favicon: null
title: Inspired
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
